# Generated by Django 4.2.3 on 2023-07-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='runTime',
            field=models.DecimalField(decimal_places=0.0, default=0, max_digits=24.0),
        ),
    ]
