# Generated by Django 4.2.3 on 2023-07-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_actor_remove_movie_cast_alter_movie_genre_movie_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(null=True, to='polls.actor'),
        ),
    ]
