# Generated by Django 4.2.3 on 2023-08-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_genre_name_alter_movie_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(to='polls.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(choices=[('G', 'General Audiences'), ('PG', 'Parental Guidance Suggested'), ('PG-13', 'Parents Strongly Cautioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only'), ('NR', 'Not Rated')], default='NR', max_length=5, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runTime',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='movie',
            name='starRating',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
